version: "3.9"

services:
  composer:
    image: composer:2.6.5
    container_name: laravel-dev_env 
    volumes:
      - ./:/app
    tty: true
    #command: tail -f /dev/null
    command: bash -c "docker-php-ext-install pdo_mysql mysqli && php -v && composer install && php artisan migrate && php artisan permission:create-role admin && php artisan permission:create-role User && php artisan serve --host=0.0.0.0 --port=5555"
    ports:
      - "5555:5555"
    depends_on:
      mariadb:
        condition: service_healthy

  node:
    image: node:20-alpine
    container_name: node20-forupdatevite
    working_dir: /app
    #command: tail -f /dev/null
    volumes:
      - ./:/app
    tty: true
    depends_on:
      - composer
    command: > 
      sh -c "npm install && npm run build "

  mariadb:
    image: mariadb:10.4.32
    container_name: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: "hellkitchen"
    tty: true
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

